In [3]:
''' 
1. Write a program to repeatedly sum the digits of a number until the result is zero.
Example:
Input: number = 123
Output: 6
Explanation: Sum of digits is 1 + 2 + 3 = 6; sum of digits of 6 is 6 (which is a single digit).
'''
x = int(input("Enter the number: "))
temp = x
sum = 0
while x!=0:
    sum += x % 10
    x = x // 10
print(f"Sum of digits of {temp}: {sum}")


Sum of digits of 123456: 21


In [2]:
''' 
2. Write a program to generate multiplication tables for numbers within a specified range.
Example:
Input: start = 2, end = 4
Output:
2 x 1 = 2   3 x 1 = 3   4 x 1 = 4  
2 x 2 = 4   3 x 2 = 6   4 x 2 = 8  
2 x 3 = 6   3 x 3 = 9   4 x 3 = 12  
2 x 4 = 8   3 x 4 = 12  4 x 4 = 16  
'''
start = int(input("Enter the starting number: "))
end = int(input("Enter the ending number: "))
for i in range(start, end+1):
    for j in range(1, end+1):
        print(f"{i} X {j} = {i*j}")
    print("\n")




2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8


3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12


4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16




In [6]:
''' 
3. Write a program to calculate the sum of the series 1 + 1/2 + 1/3 + ... + 1/n up to the nth term.
Example:
Input: n = 4
Output: 2.083333
Explanation: Sum of the series is 1 + 1/2 + 1/3 + 1/4 ≈ 2.083333.
'''
def sum_of_series(n):
    sum = 0
    for i in range(1, n+1):
        sum += 1/(i)
    return sum
def print_series(n):
    for i in range(1, n+1):
        print(f"1/{i} +", end = " ")

num = int(input("Enter the nth term of the series: "))
print("Sum of series: ")
print_series(num)
print(f" is: {sum_of_series(num)}")

Sum of series: 
1/1 + 1/2 + 1/3 + 1/4 +  is: 2.083333333333333


In [4]:
''' 
4. Write a program to find all pairs of elements in an array whose sum equals a specified target.
Example:
Input: array = [1, 2, 3, 4, 5], target = 5
Output: [(1, 4), (2, 3)]
Explanation: Pairs that sum up to 5 are (1, 4) and (2, 3).
'''
target = int(input("Enter the target: "))
array = [int(x) for x in input("Enter the array: ").split()]

print(f"Pairs that sum upto {target} are: ")
for i in array:
    for j in array:
        if i + j == target:
            print(f"({i}, {j})")


Pairs that sum upto 8 are: 
(1, 7)
(2, 6)
(3, 5)
(4, 4)
(5, 3)
(6, 2)
(7, 1)


In [12]:
''' 
5. Write a program to create a diamond pattern with stars of a given size.
Example:
Input: size = 5
Output:

  *  
 ***  
*****  
 ***  
  *  
'''
def print_diamond(size):
    mid = size // 2

    # Loop for the upper half of the diamond
    for i in range(mid + 1):
        # Print spaces
        for j in range(mid - i):
            print(" ", end="")
        # Print stars
        for j in range(2 * i + 1):
            print("*", end="")
        print()  # Move to the next line

    # Loop for the lower half of the diamond (incrementing loop)
    for i in range(1, mid + 1):
        # Print spaces
        for j in range(i):
            print(" ", end="")
        # Print stars
        for j in range(2 * (mid - i) + 1):
            print("*", end="")
        print()  # Move to the next line

# Input: size of the diamond (should be an odd number)
size = int(input("Enter an odd number for the size of the diamond: "))
if size % 2 == 0:
    print("Please enter an odd number.")
else:
    print_diamond(size)



    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


In [12]:
''' 
6. Write a program to count how many palindromic substrings exist in a given string.
Example:
Input: string = "aaa"
Output: 6
Explanation: Palindromic substrings are "a", "a", "a", "aa", "aa", "aaa".
'''

def is_palindrome(string):
    if string == string[::-1]:
        return True
    else:
        return False
    
def count_palindromic_substrings(string):
    count = 0
    for i in range(len(string)):
        for j in range(i, len(string)):
            substring = string[i:j+1]
            if substring == substring[::-1]:
                print(substring)
                count += 1
    return count

string = input("Enter the string to check for no. of palindromic substrings: ").lower()
if is_palindrome(string) == True:
    print(f"No. of palindromic substrings in a {string}: {count_palindromic_substrings(string)}")
else:
    print("Enter a valid string!")


r
radar
a
ada
d
a
r
No. of palindromic substrings in a radar: 7


In [14]:
''' 
7. Write a program to generate a matrix where each element at position (i, j) is the product of i and j.
Example:
Input: size = 3
Output:

1 2 3  
2 4 6  
3 6 9  

'''
def multiplication_table(size):
    for i in range(1, size+1):
        for j in range(1, size+1):
            print(i*j, end=" ")
        print()

size = int(input("Enter the size of required matrix: "))
multiplication_table(size)


1 2 3 4 
2 4 6 8 
3 6 9 12 
4 8 12 16 


In [6]:
'''
8. Write a program to find the GCD (Greatest Common Divisor) of an array of numbers.
Example:
Input: array = [12, 24, 36]
Output: 12
Explanation: The GCD of 12, 24, and 36 is 12.
'''
def gcd_array(arr):
    minm = min(arr)
    for i in range (minm, 0, -1):
        count = 0
        arr_length = len(arr)
        for j in arr:
            if j % i != 0:
                break
            else:
                count+=1
        if count == arr_length:
            return i
array = [int(x) for x in input("Enter the array to find GCD of: ").split()]
print(f"The greatest commond divisor of array {array}: {gcd_array(array)}")

The greatest commond divisor of array [20, 30, 60, 100]: 10


In [9]:
''' 
9. Write a program to calculate the sum of the first N odd numbers.
Example:
Input: N = 5
Output: 25
Explanation: Sum of the first 5 odd numbers (1 + 3 + 5 + 7 + 9) is 25.
'''
def sum_n_odd_numbers(n):
    sum = 0
    for i in range(n):
        sum += 2*i+1
    return sum
num = int(input("Enter the no. of odd numbers to sum: "))
print(f"Sum of first {num} odd numbers are: {sum_n_odd_numbers(num)} ")

Sum of first 21 odd numbers are: 441 


In [10]:
# easy alternative code for summing odd numbers using mathematical formula
def sum_n_odd_numbers(n):
    return n**2
num = int(input("Enter the no. of odd numbers to sum: "))
print(f"Sum of first {num} odd numbers are: {sum_n_odd_numbers(num)} ")

Sum of first 21 odd numbers are: 441 


In [2]:
''' 
10. Write a program to find how many perfect numbers exist up to a given limit.
Example:
Input: limit = 30
Output: 1
Explanation: There is only one perfect number (6) up to 30.
'''
def count_perfect_numbers(lim):
    count = 0
    for i in range(1, lim+1):
        summ = 0
        for j in range(1, int(i/2)+1):
            if i % j == 0:
                summ += j
        if summ == i:
            count += 1
    return count

limit = int(input("Enter the limit upto which no. of perfect number is to be counted: "))
print(f"No. of perfect numbers upto {limit}: {count_perfect_numbers(limit)}")

No. of perfect numbers upto 30: 2


In [6]:
''' 
11. Write a program to find the largest prime factor of a given number.
Example:
Input: number = 28
Output: 7
Explanation: The prime factors of 28 are 2 and 7, with the largest being 7.
'''
def is_prime(a):
    for i in range(2, int(a/2)+1):
        if a % i == 0:
            return False
    return True



def largest_prime_factor(num):
    pr_factors = []
    for i in range(1, num+1):
        if num % i == 0:
            if is_prime(i):
                pr_factors.append(i)
    return max(pr_factors)

number = int(input("Enter a number to find a highest prime factor of: "))
print(f"The highest prime factor of {number} is: {largest_prime_factor(number)}")

The highest prime factor of 676 is: 13


In [4]:
''' 
12. Write a program to generate a matrix where each element is a Fibonacci number.
Example:
Input: size = 3
Output:

1 1 2  
3 5 8  
13 21 34  
'''
def generate_fibonacci_series(size):
    req_size = size*size
    a = 1
    b = 1
    fib = []
    for i in range (req_size):
        fib.append(a)
        c = a + b
        a = b
        b = c
    return fib

def gen_matrix_for_fibonacci_series(fibo, size):
    k = 0
    for i in range(size):
        for j in range(size):
            print(fibo[k], end=" ")
            k += 1
        print()

x = int(input("Enter the size of matrix: "))

fib_series = generate_fibonacci_series(x)
gen_matrix_for_fibonacci_series(fib_series, x)

1 1 2 3 
5 8 13 21 
34 55 89 144 
233 377 610 987 


In [19]:
''' 
12. Write a program to calculate the sum of the first N prime numbers.
Example:
Input: N = 4
Output: 17
Explanation: The sum of the first 4 prime numbers (2 + 3 + 5 + 7) is 17.
'''
def is_prime(num):
    if num == 0 or num == 1:
        return False
    for i in range(2, int(num/2)+1):
        if num % i == 0:
            return False
    return True

def sum_primes(size):
    count = 0
    sum_p = 0
    num = 2
    while count != size:
        if is_prime(num):
            sum_p += num
            count += 1
        num += 1
    return sum_p

x = int(input("Enter the no. of prime numbers to sum: "))
print(f"The Sum of first {x} prime numbers is: {sum_primes(x)}")


The Sum of first 5 prime numbers is: 28


In [4]:
''' 
14. Write a program to check if a given string with brackets is balanced.
Example:
Input: string = "{[()]}"
Output: True
Explanation: The brackets are balanced.
'''
def is_balanced(s):
    stack = []
    for i in s:
        if i in ['[', '{', '(']:
            stack.append(i)
        if i in [']', '}', ')']:
            stack.pop()
    if len(stack) == 0:
        return True
    return False

string = input("Enter the string to check for balance of brackets: ")
if is_balanced(string):
    print(f"The given string: {string} is balanced")
else:
    print(f"The given string: {string} is not balanced")


The given string: ([}{]) is balanced


In [6]:
''' 
15. Write a program to extract and sum all numbers present in a given string.
Example:
Input: string = "The numbers are 12 and 34"
Output: 46
Explanation: The sum of numbers 12 and 34 is 46.
'''
import re
string = input("Enter the string with numbers: ")
numbers = re.findall(r'\d+', string)
sum_of_numbers = sum(map(int, numbers))
print(f"The sum of numbers in text: {string} is: {sum_of_numbers}")

The sum of numbers in text: the numbers are 34 and 37 is: 71


In [27]:
''' 
16. Write a program to find the longest sequence of consecutive numbers in an array.
Example:
Input: array = [100, 4, 200, 1, 3, 2]
Output: 4
Explanation: The longest consecutive sequence is [1, 2, 3, 4].
'''

array = [int(i) for i in input("Enter the array of numbers: ").split()]

array1 = array[:]
array.sort()
n = len(array)

start = array[0]
counts_list = [0]
count = 0
for i in range(n):
    if start in array:
        count += 1
        counts_list.append(count)
        start = start + 1
    else:
        start = array[i]
        count = 1 # offset
print(f"The longest sequence of consecutive numbers in {array1} is of length: {max(counts_list)}")

The longest sequence of consecutive numbers in [3, 8, 5, 7, 6] is of length: 4


In [8]:
''' 
17: Write a program to generate a matrix filled with numbers in a spiral pattern.
Example:
Input: size = 3
Output:

1 2 3  
8 9 4  
7 6 5  
'''
def generate_spiral_matrix(size):
    # Initialize an empty matrix
    matrix = [[0] * size for _ in range(size)]
    
    # Initialize the boundaries
    left, right = 0, size - 1
    top, bottom = 0, size - 1
    num = 1  # Starting number to fill the matrix
    
    # Fill the matrix in a spiral order
    while left <= right and top <= bottom:
        # Fill the top row from left to right
        for i in range(left, right + 1):
            matrix[top][i] = num
            num += 1
        top += 1
        
        # Fill the right column from top to bottom
        for i in range(top, bottom + 1):
            matrix[i][right] = num
            num += 1
        right -= 1
        
        # Fill the bottom row from right to left
        for i in range(right, left - 1, -1):
            matrix[bottom][i] = num
            num += 1
        bottom -= 1
        
        # Fill the left column from bottom to top
        for i in range(bottom, top - 1, -1):
            matrix[i][left] = num
            num += 1
        left += 1
    
    return matrix

# Test the function
size = int(input("Enter the size of matrix: "))
spiral_matrix = generate_spiral_matrix(size)

# Print the matrix in a formatted way
for row in spiral_matrix:
    print(" ".join(map(str, row)))


1 2 3 4
12 13 14 5
11 16 15 6
10 9 8 7


In [13]:
''' 
18. Write a program to generate all possible subsets of a given set of numbers.
Example:
Input: set = [1, 2]
Output: [[], [1], [2], [1, 2]]
Explanation: The subsets of [1, 2] are the empty set, [1], [2], and [1, 2]
'''
from itertools import combinations

def gen_subsets(arr):
    subsets = []
    for i in range(len(arr)+1):
        comb = combinations(arr, i)
        for c in comb:
            subsets.append(list(c))
    print(f"The possible subsets of {arr} are: {subsets}")

nums = [int(_) for   _ in input("Enter the set to find subsets  of:").split()]
gen_subsets(nums)


The possible subsets of [1, 2, 5] are: [[], [1], [2], [5], [1, 2], [1, 5], [2, 5], [1, 2, 5]]


In [16]:
''' 
19. Write a program to check which numbers in a given range are perfect squares.
Example:
Input: start = 1, end = 10
Output: [1, 4, 9]
Explanation: Perfect squares between 1 and 10 are 1, 4, and 9.
'''
import math
def perfect_squared(start, end):
    perfectos = []
    for i in range(start, end+1):
        if math.sqrt(i) == int(math.sqrt(i)):
            perfectos.append(i)
    return perfectos

starts_at = int(input("Enter the starting number: "))
ends_at = int(input("Enter the ending number: "))
print(f" The perfect squares between {starts_at} and {ends_at} are: {perfect_squared(starts_at, ends_at)}")

 The perfect squares between 1 and 50 are: [1, 4, 9, 16, 25, 36, 49]


In [1]:
'''
20. Write a program to calculate the sum of the diagonal elements in a square matrix.
Example:
Input: matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Output: 15
Explanation: The sum of the diagonal elements (1 + 5 + 9) is 15.
'''
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

def calculate_diagonal_sum(matrix):
    sum_d = 0
    for i in range(len(matrix)):
        sum_d += matrix[i][i]
    return sum_d

print(f"The sum of diagonal elements of {matrix} is: {calculate_diagonal_sum(matrix)}")


The sum of diagonal elements of [[1, 2, 3], [4, 5, 6], [7, 8, 9]] is: 15


In [5]:
'''
21. Write a program to find the second smallest number in an array.
Example:
Input: array = [12, 13, 1, 10, 34, 1]
Output: 10
Explanation: The second smallest number in the array is 10.
'''
array = [int(i) for i in input("Enter the elements of the array").split()]
y = array[:]
y.sort(reverse= True)
print(f"The second largest element of the {array} is: {y[1]}")

The second largest element of the [12, 13, 1, 10, 34, 1] is: 13


In [ ]:
''' 
22. Write a program to generate Pascal’s Triangle up to N rows.
Example:
Input: N = 3
Output:

1  
1 1  
1 2 1  

'''
def pascal(rows):
    for n in range(rows+1):
        ncr = 1
        for r in range(1, n+1):
            print(ncr, " ", sep='', end='')
            ncr = ncr * (n - r) // r
        print()

x = int(input("Enter no. of rows: "))
pascal(x)


1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 


In [2]:
''' 
23. Write a program to find the sum of the digits of the product of two given numbers.
Example:
Input: number1 = 12, number2 = 34
Output: 9
Explanation: The product of 12 and 34 is 408, and the sum of its digits is 4 + 0 + 8 = 12.
'''
def multiply(num1, num2):
    return num1 * num2

number1 = int(input("Enter the 1st number: "))
number2 = int(input("Enter the 2nd number: "))
product = multiply(number1, number2)
sum_of_digits = sum(int(digit) for digit in str(product))
print(f" The product of {number1} and {number2} is: {product} and Sum of digits of {product} is: {sum_of_digits}")


 The product of 45 and 89 is: 4005 and Sum of digits of 4005 is: 9


In [7]:
''' 
24. Write a program to check for palindromic numbers within a given range.
Example:
Input: start = 1, end = 100
Output: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 22, 33, 44, 55, 66, 77, 88, 99]
Explanation: Palindromic numbers between 1 and 100 are the numbers listed.
'''

down = int(input("Enter the lower range: "))
up = int(input("Enter the upper range: "))

def palindromes(down, up):
    palindromes = []
    for i in range(down, up+1):
        if str(i) == str(i)[::-1]:
            palindromes.append(i)
    return palindromes

print(f"Palindromes in between {down} and {up} are: {palindromes(down, up)}")



Palindromes in between 1 and 100 are: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 22, 33, 44, 55, 66, 77, 88, 99]


In [ ]:
'''
25. Write a program to generate a matrix where the elements alternate between 0 and 1.
Example:
Input: size = 3
Output:

0 1 0  
1 0 1  
0 1 0  

'''
import numpy as np
size = int(input("Enter the size of matrix: "))

def gen_alternate_arr(size):
    alternate_array = []
    for i in range(size*size):
        if i % 2 == 0:
            alternate_array.append(0)
        else:
            alternate_array.append(1)
    return alternate_array
array = np.array(gen_alternate_arr(size))

def gen_matrix(array, size):
    matrix = array.reshape(size, size)
    for row in matrix:
        print(row)
gen_matrix(array, size)

[0 1 0 1 0]
[1 0 1 0 1]
[0 1 0 1 0]
[1 0 1 0 1]
[0 1 0 1 0]


In [5]:
''' 
26. Write a program to count how many times a specific word appears in a given string.
Example:
Input: string = "hello world hello"
Output: 2
Explanation: The word "hello" appears 2 times in the string.
'''
string = input("Enter the string: ")
word = input("Enter the word to count repetition for, in the string: ")

def count_word(string, word):
    count = 0
    for i in string.split():
        if i == word:
            count += 1
    return count

print(f"The word: {word} appears {count_word(string, word)} times in \"{string}\"")


The word: boom appears 2 times in "shaka laka boom boom"


In [14]:
''' 
27. Write a program to find the largest sum of any contiguous subarray.
Example:
Input: array = [-2, 1, -3, 4, -1, 2, 1, -5, 4]
Output: 6
Explanation: The largest sum is 6, from the subarray [4, -1, 2, 1]
'''
array = [int(i) for i in input("Enter the array elements: ").split()]
# array = [2, 3, -8, 7, -1, 2, 3]
array_length = len(array)
subarray = []
max_sum = array[0]
for i in range(array_length):
    for j in range(i, array_length):
        subarray_sum = sum(array[i:j+1])
        if max_sum < subarray_sum:
            max_sum = int(subarray_sum)
            subarray.append(array[i:j+1])

print(f"largest sum is: {max_sum} of continguous Subarray: {subarray[-1]}")

largest sum is: 11 of continguous Subarray: [7, -1, 2, 3]


In [16]:
''' 
28. Write a program to create a right-angle triangle pattern with numbers.
Example:
Input: height = 4
Output:

1  
12  
123  
1234  

'''
height = int(input("Enter the height for pattern: "))
for i in range(1, height + 1):
    for j in range(1, i+1):
        print(j, end='')
    print()

1
12
123
1234


In [3]:
''' 
29. Write a program to find all divisors of the product of two given numbers.
Example:
Input: number1 = 6, number2 = 10
Output: [1, 2, 3, 5, 6, 10, 15, 30]
Explanation: The product of 6 and 10 is 60, and its divisors are listed.
'''
def find_divisors(num1, num2):
    product = num1 * num2
    divisors = []
    for num in range(1, int(product/2)+1):
        if product % num == 0:
            divisors.append(num)
    return divisors
num1 = int(input("Enter 1st number: "))
num2 = int(input("Enter 2nd number: "))
print(f"The divisors of product of {num1} and {num2} are: {find_divisors(num1, num2)}")

The divisors of product of 6 and 10 are: [1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30]


In [ ]:
''' 
30. Write a program to find the longest sequence of consecutive 1s in a binary array.
Example:
Input: array = [1, 1, 0, 1, 1, 1]
Output: 3
Explanation: The longest sequence of 1s is [1, 1, 1] with length 3.
'''
def longest_sequence_of_ones(arr):
    count = 0
    counts = []
    for i in arr:
        if i == 0:
            counts.append(count)
            count = 0
        if i == 1:
            count += 1
    counts.append(count)
    return max(counts)

array = [int(i) for i in input("Enter the binary array: ").split()]
print(f"The longest sequence of 1s in {array} is of length: {longest_sequence_of_ones(array)}")


The longest sequence of 1s in [1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1] is: 7


In [14]:
''' 
31. Write a program to calculate the sum of the first N Fibonacci numbers.
Example:
Input: N = 5
Output: 12
Explanation: The first 5 Fibonacci numbers are 1, 1, 2, 3, 5, and their sum is 12.
'''
def sum_n_fib_seq(size):
    if size <= 1:
        return size
    else:
        return sum_n_fib_seq(size-1) + sum_n_fib_seq(size-2)
    
size = int(input("Enter the no. of elements in fibonacci sequence to sum: "))
seq = []
for i in range(1, size+1):
    seq.append(sum_n_fib_seq(i))
print(f" Sum of first {size} fibonacci numbers, {seq}: {sum(seq)}")

 Sum of first 7 fibonacci numbers, [1, 1, 2, 3, 5, 8, 13]: 33
